# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ShareWithInstagram' do
	# Uncomment this line if you're using Swift or would like to use dynamic frameworks
	# use_frameworks!

	# Pods for ShareWithInstagram
	pod "MGInstagram"
	pod "PKImagePicker"

	target 'ShareWithInstagramTests' do
		inherit! :search_paths
		# Pods for testing
	end

	target 'ShareWithInstagramUITests' do
		inherit! :search_paths
		# Pods for testing
	end

end
